### ISSUE TITLE
testgetdests waits indefinitely

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/libcups#33]
Hi,

I've tried to run the test suite to verify my PR, it gets stuck on ```cupsGetDests()``` function - here is the 
[strace.txt](https://github.com/OpenPrinting/libcups/files/9830020/strace.txt).

Is it expected to work without CUPS 3.0 Local module?

I've configured and compiled the project like this:

```
$ ./configure
$ make
$ make test
```

**Comment by michaelrsweet** [comment]
OK, so "testgetdests" loops indefinitely. Changing to do a single test by default.

**Comment by michaelrsweet** [comment]
So it looks like the change has exposed a DNS-SD bug. Investigating...

**Comment by michaelrsweet** [comment]
It was a threading bug which I seem to have fixed...

[master 1428bee0a] Fix threading bug in DNS-SD API (Issue #33)

Still getting a "bad file descriptor" error in the Linux CI system, but we are probably not finding the cupsd socket...
