### ISSUE TITLE
ipptool: add a "$basename" variable

### ISSUE THREAD

**Issue by wifiprintguy** [OpenPrinting/libcups#44]
The $filename variable provides the entire path specified by the -f option. It would be nice if there was a way to trim that to its "basename" component (last element in the path) for when the filename is used in job naming, such as:

`ATTR name "job-name" "Some test $user $basename $job-id" `

so that looking at the job log can be useful when testing.

Moved https://github.com/istopwg/ippsample/issues/277 here as per guidance from @michaelrsweet.

**Comment by michaelrsweet** [comment]
[master fa3415661] Add basename variable (Issue #44)
