### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [OpenPrinting/libcups#55]
:thought_balloon: Did the software situation evolve in ways which can it eventually make more attractive to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/OpenPrinting/libcups/blob/8368a3b31d4d156f3ad8f74702e24a6fef789adb/configure.ac#L236 "Update candidate")?

**Comment by michaelrsweet** [comment]
No.
