### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [OpenPrinting/libcups#56]
I would like to point out that identifiers like “[`_CUPS_FILE_H_`](https://github.com/OpenPrinting/libcups/blob/8368a3b31d4d156f3ad8f74702e24a6fef789adb/cups/file.h#L17 "Update candidate")” and “[`_CUPS_IPP_H_`](https://github.com/OpenPrinting/libcups/blob/8368a3b31d4d156f3ad8f74702e24a6fef789adb/cups/ipp.h#L12 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by michaelrsweet** [comment]
No.

**Comment by elfring** [comment]
:thought_balloon: How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
