### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [OpenPrinting/libcups#57]
Would you like to add more error handling for return values from functions like the following?
* [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [cupsMutexInit](https://github.com/OpenPrinting/libcups/blob/8368a3b31d4d156f3ad8f74702e24a6fef789adb/cups/thread.c#L493)
* [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [cupsDNSSDServiceNew](https://github.com/OpenPrinting/libcups/blob/8368a3b31d4d156f3ad8f74702e24a6fef789adb/cups/dnssd.c#L1252)

**Comment by michaelrsweet** [comment]
Sorry, but these sorts of bug reports are worse than useless.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by elfring** [comment]
:thought_balloon: Can you adhere to [secure programming guidelines](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "EXP12-C: Do not ignore values returned by functions")?
