### ISSUE TITLE
Unable to build on Mac M1 when openssl is installed with Brew

### ISSUE THREAD

**Issue by godofecht** [OpenPrinting/libcups#64]
**Commands Used**
```
1073  sudo ./configure
1074  sudo make all
```

Linking libcups3.3.dylib...
ld: warning: ignoring file /opt/homebrew/Cellar/openssl@3/3.1.2/lib/libssl.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/openssl@3/3.1.2/lib/libcrypto.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64

**Comment by michaelrsweet** [comment]
The default on macOS is to build Universal Binaries. There are two ways to change this:

1. Use the `--enable-debug` option
2. Add `-arch arm64` to the CFLAGS and LDFLAGS environment variables or the OPTIM environment variable.
