### ISSUE TITLE
Migrate ipptransform to this project

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/libcups#65]
The [ippsample](https://github.com/istopwg/ippsample) project currently hosts the ipptransform tool, but it belongs in this project so it can be more widely used.

**Comment by michaelrsweet** [comment]
Initial check-in, still need to do localization and add PostScript (bitmap) output.

[master efac5082e] Initial checkin of ipptransform and PDFio code (Issue #65)

**Comment by michaelrsweet** [comment]
[master 5203058d5] Add basic PostScript (image) support to ipptransform (Issue #65)

**Comment by attah** [comment]
Very nice! This makes my "pdf2printable" all but redundant (and that's a good thing).
Especially impressive that you could get mixed-orientation PDFs to come out usable from pdftoppm.

It seems you made a copy-paste error in the ps_end_page code; it looks very much like just another pcl_end_page.
If i replace it with a single "showpage" it comes out rotated, so presumably it needs something more.

(And the ps_start_* refer to PCL in their comments).

**Comment by michaelrsweet** [comment]
@attah Yes, what is in the repo is an incomplete work-in-progress. Ultimately this program is what will get used to convert print files into something a printer will accept for the local and sharing servers, as well as doing some of the higher-level manipulation/scaling/imposition functions. The output formats are intentionally limited but we'll need PCL and PostScript support for printing to legacy Windows print servers.

**Comment by michaelrsweet** [comment]
[master 0115e2334] Add localization to ipptransform.
