### ISSUE TITLE
Segfault when using cupsGetDests

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/libcups#74]
### Discussed in https://github.com/OpenPrinting/libcups/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **NJRoadfan** January 12, 2024</sup>
Hello,

I am [working on](https://github.com/Netatalk/netatalk/issues/663) updating some code to support libcups3. I am at the point that I would like to test against the actual libcups3 library. How would one go about doing this? Can libcups3 co-exist with an existing CUPS 2.x install? Or do I have to start fresh with a new Linux VM without any CUPS packages installed and build libcups3?

Also, is the cups-local server needed to print? If so, I'll have to build/install it as well. My existing code calls libcups to submit a job (ultimately a PDF) via cupsCreateDestJob() and cupsStartDestDocument().</div>

**Comment by NJRoadfan** [comment]
Adding some details here to reproduce.

Test environment:
Hardware: Raspberry Pi 400
OS: Raspberry Pi OS (Debian 11 "bullseye")

Running CUPS 2.3.3op2 included with OS with one printer queue, the CUPS-PDF printer.

Steps to reproduce:
-Clone current master of libcups3
-Configure with --prefix=/usr/
-Compile and install
-Built the "simple" application in the CUPS API docs that calls cupsEnumDests() and prints out the results.
-Application segfaults when calling cupsEnumDests().

Issue is not just limited to calling cupsEnumDests(). The application I am testing and updating for libcups3 support is also segfaulting when calling cupsGetDests().

Note: I tried testing with the tagged 3.0b2 release. It does not segfault, but still has issues. The sample application outputs a list of printer destinations and then hangs. Have to Ctrl-C at that point.

**Comment by michaelrsweet** [comment]
OK, so the segfault is an easy fix - the value formatter didn't handle dateTime values...

The hang is occurring when shutting down the DNS-SD thread, not sure why yet.

**Comment by michaelrsweet** [comment]
Looks like zdohnal fixed the hang in CUPS 2.5, so I brought that fix over:

[master 778600ccc] Fix hang and crash in cupsGetDests (Issue #74)

**Comment by NJRoadfan** [comment]
Just synced the changes and re-built. Looks like everything is working now, including my project. 👍
