### ISSUE TITLE
IPP-2.1.test does not exist

### ISSUE THREAD

**Issue by SerinitySW** [OpenPrinting/libcups#85]
**Describe the bug**
It seems the git repo does not come with ipp-2.1.test, causing failure when running `make install`.

**To Reproduce**
1. Clone libcups repo
2. Run `./configure`
3. Run `make`
4. Run `make install`

**Expected behavior**
ipp-2.1.test should ideally exist in the repo

**System Information:**
 - OS: Debian 12 Bookworm (Raspbian)
 - Browser Chrome and Firefox
 - Version v3.0b2

**Additional context**
I attempted to simply make a copy of ipp-2.0.test, renaming it to ipp-2.1.test to no avail. I am attempting to install this beta version of OpenPrinting's CUPS because I couldn't get ssl working at all (even with default files) on CUPS 2.5b1.

**Comment by SerinitySW** [comment]
I managed to find examples/Makerfile and edited it to remove the lines:

lib-2.1.test
lib-2.2.test
ipp-backend.test
ipp-everywhere.test

Which allows `make install` to run successfully, however /etc/cups is missing and the WebUI is unavailable.

**Comment by michaelrsweet** [comment]
Please note: the libcups repository only provides the CUPS library and "ipp" tools for a future set of CUPS servers (cupslocald and cupssharingd) in the other cups-xxx projects.

**Comment by michaelrsweet** [comment]
Also, please report your SSL issues to the CUPS project since that will be the next stable version.

**Comment by milahu** [comment]
version 6fe4c090763590df9084b726a1815198f2c3233e (3.0b2) fails with

```
======== install in examples ========
make[1]: Entering directory '/build/source/examples'
Installing sample ipptool files in /nix/store/hkvzza6c6zrfmmcl44p579r39rqw2riv-libcups-3.0b2/share/libcups3/ipptool...
install: ipp-2.1.test does not exist
```

version 7a8ff5880e878c10e2604c1a59897f8f77ff2d80 fails with

```
======== all in pdfio ========
make[1]: Entering directory '/build/source/pdfio'
make[1]: *** No rule to make target 'all'.  Stop.
```

**Comment by michaelrsweet** [comment]
OK, I've restored and updated the IPP/2.x conformance (and related) files for the 3.0rc1 release.
