### ISSUE TITLE
embedded pdfio fails to build

### ISSUE THREAD

**Issue by milahu** [OpenPrinting/libcups#86]
version 7a8ff5880e878c10e2604c1a59897f8f77ff2d80 (151 commits after 3.0b2) fails with

```
checking for pdfio library... no, using embedded version

...

======== all in pdfio ========
make[1]: Entering directory '/build/source/pdfio'
make[1]: *** No rule to make target 'all'.  Stop.
```

workaround: build `libcups` with shared external `pdfio` library

see also my build script in [libcups.nix](https://github.com/milahu/nur-packages/raw/master/pkgs/applications/printing/libcups/default.nix)

this was part of https://github.com/OpenPrinting/libcups/issues/85#issuecomment-2293059842

**Comment by michaelrsweet** [comment]
You need to check out the submodule, too…

not sure how you tell it to do so in your build script, but the Git source requires it.

**Comment by milahu** [comment]
pacepalm. yes, of course.

in my `libcups.nix` that would be

```
  src = fetchFromGitHub {
    owner = "OpenPrinting";
    repo = "libcups";
    rev = "7a8ff5880e878c10e2604c1a59897f8f77ff2d80";
    hash = "sha256-HclC997yuqQdc4IChp/AovV9UdSAyKvpDyYexZ/Cwio=";
    fetchSubmodules = true;
  };
```
